#!/usr/bin/env node

process.stdin.resume();
process.stdin.setEncoding("utf8");

alldate = [];

process.stdin.on("data", function(chunk){
  alldate.push(translate(chunk));
});

process.stdin.on("end", function(){
  process.stdout.write(alldate.join("\n"));
});

function translate(line){
  return ".f(" + line + ")"
}